/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaBean;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Alejandro
 */
public class BeanColores extends javax.swing.JPanel {

    /**
     * Creates new form BeanColores
     */
    public BeanColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColores = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();
        jRadioButtonAmarillo = new javax.swing.JRadioButton();
        jPanelColor = new javax.swing.JPanel();

        jLabel1.setText("Semáforo");

        buttonGroupColores.add(jRadioButtonRojo);
        jRadioButtonRojo.setText("Rojo");
        jRadioButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRojoActionPerformed(evt);
            }
        });

        buttonGroupColores.add(jRadioButtonAzul);
        jRadioButtonAzul.setText("Azul");
        jRadioButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAzulActionPerformed(evt);
            }
        });

        buttonGroupColores.add(jRadioButtonAmarillo);
        jRadioButtonAmarillo.setText("Amarillo");
        jRadioButtonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmarilloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAzul)
                            .addComponent(jRadioButtonRojo)
                            .addComponent(jRadioButtonAmarillo))
                        .addGap(48, 48, 48)
                        .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jRadioButtonRojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonAzul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAmarillo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRojoActionPerformed
        // TODO add your handling code here:
        jPanelColor.setBackground(Color.red);
        
    }//GEN-LAST:event_jRadioButtonRojoActionPerformed

    private void jRadioButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAzulActionPerformed
        // TODO add your handling code here:
        jPanelColor.setBackground(Color.blue);
    }//GEN-LAST:event_jRadioButtonAzulActionPerformed

    private void jRadioButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmarilloActionPerformed
        // TODO add your handling code here:
        jPanelColor.setBackground(Color.yellow);
    }//GEN-LAST:event_jRadioButtonAmarilloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JRadioButton jRadioButtonAmarillo;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonRojo;
    // End of variables declaration//GEN-END:variables

    public ButtonGroup getButtonGroupColores() {
        return buttonGroupColores;
    }

    public void setButtonGroupColores(ButtonGroup buttonGroupColores) {
        this.buttonGroupColores = buttonGroupColores;
    }

    public JRadioButton getjRadioButtonAmarillo() {
        return jRadioButtonAmarillo;
    }

    public void setjRadioButtonAmarillo(JRadioButton jRadioButtonAmarillo) {
        this.jRadioButtonAmarillo = jRadioButtonAmarillo;
    }

    public JRadioButton getjRadioButtonAzul() {
        return jRadioButtonAzul;
    }

    public void setjRadioButtonAzul(JRadioButton jRadioButtonAzul) {
        this.jRadioButtonAzul = jRadioButtonAzul;
    }

    public JRadioButton getjRadioButtonRojo() {
        return jRadioButtonRojo;
    }

    public void setjRadioButtonRojo(JRadioButton jRadioButtonRojo) {
        this.jRadioButtonRojo = jRadioButtonRojo;
    }
}
